export const universityCities = [
  'Aberdeen',
  'Aberystwyth',
  'Aston',
  'Bath',
  'Birmingham',
  'Bristol',
  'Cambridge',
  'Cardiff',
  'Chester',
  'Dundee',
  'Durham',
  'Edinburgh',
  'Exeter',
  'Falmouth University',
  'Glasgow',
  'Hull',
  'Kent',
  'King\'s College London',
  'Lancaster',
  'Leeds',
  'Leicester',
  'Lincoln',
  'Liverpool',
  'LSE',
  'Liverpool John Moores',
  'Loughborough',
  'Manchester',
  'Newcastle',
  'Northumbria',
  'Nottingham',
  'Nottingham Trent',
  'Oxford',
  'Oxford Brookes',
  'Plymouth',
  'Portsmouth',
  'Queen Mary',
  'Queen\'s University Belfast',
  'Reading',
  'Royal Holloway',
  'Sheffield',
  'Southampton',
  'St Andrews',
  'St George\'s',
  'Strathclyde',
  'Stirling',
  'Sussex',
  'UCLan',
  'UEA',
  'University College London',
  'UWE',
  'Warwick',
  'York',
];

export const courses = [
  'Accounting',
  'American Studies',
  'Anthropology',
  'Art',
  'Art History',
  'Biology',
  'Business Studies',
  'Chemistry',
  'Computer Science',
  'Criminology',
  'Drama',
  'Economics',
  'English',
  'English Literature',
  'Film Studies',
  'Finance',
  'French',
  'Geography',
  'German',
  'History',
  'Journalism',
  'Law',
  'Marketing',
  'Maths',
  'Media',
  'Music',
  'Nursing',
  'Philosophy',
  'Physics',
  'Politics',
  'Psychology',
  'Religious Studies',
  'Sociology',
  'Spanish',
  ];